on: 
  issue_comment:
    types: [created]
name: Bot
jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && github.event.comment.body == 'format!'
    steps:
    - name: Format the code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: .github/format.sh
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && github.event.comment.body == 'rebase!'
    runs-on: ubuntu-latest
    steps:
    - name: Automatic Rebase
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: .github/rebase.sh
